version: "3.2"

services:
  sonarqube:
    image: sonarqube:10.2-community
    container_name: sonarqube
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
